### ISSUE TITLE
Examples of how to use?

### ISSUE THREAD

**Issue by milesj** [amkartashov/bazel-remote-apis-rust#1]
Excited to see that this library exists! Was dreading having to build this functionality myself and would rather use a crate.

However, there's a lot of generated code here and I'm wondering what the best way to use it is. Some examples would be great!

**Comment by amkartashov** [comment]
@milesj this is just compiled protobuf, only structs and generic traits are here. You can check tonic docs for examples how to implement your own grpc client or server: https://github.com/hyperium/tonic/blob/master/examples/helloworld-tutorial.md

**Comment by milesj** [comment]
Awesome thank you. Haven't used tonic before but looks cool.
